import type { Mutasi, CreateMutasiInput, MutasiQueryOptions } from '@/types/mutasi';
export declare const useMutasiStore: import("pinia").StoreDefinition<"mutasi", Pick<{
    mutasiList: import("vue").Ref<{
        idMutasi: number;
        idPegawai: number;
        idJabatanLama: number;
        idJabatanBaru: number;
        idDepartemenLama: number;
        idDepartemenBaru: number;
        tanggal: string;
        jenisMutasi: "promosi" | "demosi" | "rotasi" | "transfer";
        alasan: string;
        idAdmin: number;
        createdAt: string;
        updatedAt: string;
        pegawai?: any;
        admin?: any;
    }[], Mutasi[] | {
        idMutasi: number;
        idPegawai: number;
        idJabatanLama: number;
        idJabatanBaru: number;
        idDepartemenLama: number;
        idDepartemenBaru: number;
        tanggal: string;
        jenisMutasi: "promosi" | "demosi" | "rotasi" | "transfer";
        alasan: string;
        idAdmin: number;
        createdAt: string;
        updatedAt: string;
        pegawai?: any;
        admin?: any;
    }[]>;
    currentMutasi: import("vue").Ref<{
        idMutasi: number;
        idPegawai: number;
        idJabatanLama: number;
        idJabatanBaru: number;
        idDepartemenLama: number;
        idDepartemenBaru: number;
        tanggal: string;
        jenisMutasi: "promosi" | "demosi" | "rotasi" | "transfer";
        alasan: string;
        idAdmin: number;
        createdAt: string;
        updatedAt: string;
        pegawai?: any;
        admin?: any;
    } | null, Mutasi | {
        idMutasi: number;
        idPegawai: number;
        idJabatanLama: number;
        idJabatanBaru: number;
        idDepartemenLama: number;
        idDepartemenBaru: number;
        tanggal: string;
        jenisMutasi: "promosi" | "demosi" | "rotasi" | "transfer";
        alasan: string;
        idAdmin: number;
        createdAt: string;
        updatedAt: string;
        pegawai?: any;
        admin?: any;
    } | null>;
    isLoading: import("vue").Ref<boolean, boolean>;
    error: import("vue").Ref<string | null, string | null>;
    fetchMutasiList: (options?: MutasiQueryOptions) => Promise<void>;
    getMutasiById: (id: number) => Promise<any>;
    fetchMutasiByPegawai: (idPegawai: number) => Promise<void>;
    createMutasi: (data: CreateMutasiInput) => Promise<any>;
}, "error" | "isLoading" | "mutasiList" | "currentMutasi">, Pick<{
    mutasiList: import("vue").Ref<{
        idMutasi: number;
        idPegawai: number;
        idJabatanLama: number;
        idJabatanBaru: number;
        idDepartemenLama: number;
        idDepartemenBaru: number;
        tanggal: string;
        jenisMutasi: "promosi" | "demosi" | "rotasi" | "transfer";
        alasan: string;
        idAdmin: number;
        createdAt: string;
        updatedAt: string;
        pegawai?: any;
        admin?: any;
    }[], Mutasi[] | {
        idMutasi: number;
        idPegawai: number;
        idJabatanLama: number;
        idJabatanBaru: number;
        idDepartemenLama: number;
        idDepartemenBaru: number;
        tanggal: string;
        jenisMutasi: "promosi" | "demosi" | "rotasi" | "transfer";
        alasan: string;
        idAdmin: number;
        createdAt: string;
        updatedAt: string;
        pegawai?: any;
        admin?: any;
    }[]>;
    currentMutasi: import("vue").Ref<{
        idMutasi: number;
        idPegawai: number;
        idJabatanLama: number;
        idJabatanBaru: number;
        idDepartemenLama: number;
        idDepartemenBaru: number;
        tanggal: string;
        jenisMutasi: "promosi" | "demosi" | "rotasi" | "transfer";
        alasan: string;
        idAdmin: number;
        createdAt: string;
        updatedAt: string;
        pegawai?: any;
        admin?: any;
    } | null, Mutasi | {
        idMutasi: number;
        idPegawai: number;
        idJabatanLama: number;
        idJabatanBaru: number;
        idDepartemenLama: number;
        idDepartemenBaru: number;
        tanggal: string;
        jenisMutasi: "promosi" | "demosi" | "rotasi" | "transfer";
        alasan: string;
        idAdmin: number;
        createdAt: string;
        updatedAt: string;
        pegawai?: any;
        admin?: any;
    } | null>;
    isLoading: import("vue").Ref<boolean, boolean>;
    error: import("vue").Ref<string | null, string | null>;
    fetchMutasiList: (options?: MutasiQueryOptions) => Promise<void>;
    getMutasiById: (id: number) => Promise<any>;
    fetchMutasiByPegawai: (idPegawai: number) => Promise<void>;
    createMutasi: (data: CreateMutasiInput) => Promise<any>;
}, never>, Pick<{
    mutasiList: import("vue").Ref<{
        idMutasi: number;
        idPegawai: number;
        idJabatanLama: number;
        idJabatanBaru: number;
        idDepartemenLama: number;
        idDepartemenBaru: number;
        tanggal: string;
        jenisMutasi: "promosi" | "demosi" | "rotasi" | "transfer";
        alasan: string;
        idAdmin: number;
        createdAt: string;
        updatedAt: string;
        pegawai?: any;
        admin?: any;
    }[], Mutasi[] | {
        idMutasi: number;
        idPegawai: number;
        idJabatanLama: number;
        idJabatanBaru: number;
        idDepartemenLama: number;
        idDepartemenBaru: number;
        tanggal: string;
        jenisMutasi: "promosi" | "demosi" | "rotasi" | "transfer";
        alasan: string;
        idAdmin: number;
        createdAt: string;
        updatedAt: string;
        pegawai?: any;
        admin?: any;
    }[]>;
    currentMutasi: import("vue").Ref<{
        idMutasi: number;
        idPegawai: number;
        idJabatanLama: number;
        idJabatanBaru: number;
        idDepartemenLama: number;
        idDepartemenBaru: number;
        tanggal: string;
        jenisMutasi: "promosi" | "demosi" | "rotasi" | "transfer";
        alasan: string;
        idAdmin: number;
        createdAt: string;
        updatedAt: string;
        pegawai?: any;
        admin?: any;
    } | null, Mutasi | {
        idMutasi: number;
        idPegawai: number;
        idJabatanLama: number;
        idJabatanBaru: number;
        idDepartemenLama: number;
        idDepartemenBaru: number;
        tanggal: string;
        jenisMutasi: "promosi" | "demosi" | "rotasi" | "transfer";
        alasan: string;
        idAdmin: number;
        createdAt: string;
        updatedAt: string;
        pegawai?: any;
        admin?: any;
    } | null>;
    isLoading: import("vue").Ref<boolean, boolean>;
    error: import("vue").Ref<string | null, string | null>;
    fetchMutasiList: (options?: MutasiQueryOptions) => Promise<void>;
    getMutasiById: (id: number) => Promise<any>;
    fetchMutasiByPegawai: (idPegawai: number) => Promise<void>;
    createMutasi: (data: CreateMutasiInput) => Promise<any>;
}, "fetchMutasiList" | "getMutasiById" | "fetchMutasiByPegawai" | "createMutasi">>;
//# sourceMappingURL=mutasi.store.d.ts.map